/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.kms.controller;import cn.zhuatech.kms.common.ApiResponse;import cn.zhuatech.kms.service.KnowledgePublicationGovernanceService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                    */
@RestController @RequestMapping("/api/enterprise/kms")public class KnowledgePublicationGovernanceController{private final KnowledgePublicationGovernanceService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                            */
public KnowledgePublicationGovernanceController(KnowledgePublicationGovernanceService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/knowledge-publication")public ApiResponse<KnowledgePublicationGovernanceService.Assessment>assess(@Valid @RequestBody KnowledgePublicationGovernanceService.Request request){return ApiResponse.ok(service.assess(request));}}
