/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.kms.service;
import cn.zhuatech.kms.common.BusinessException; import cn.zhuatech.kms.dto.KmsDto.*; import cn.zhuatech.kms.model.*; import cn.zhuatech.kms.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class KmsService {
    private final KnowledgeArticleRepository orders; private final ContributionRecordRepository reports; private final ExpertRepository expert; private final ReviewTaskRepository reviewTasks; private final CurrentUserService current;
    public KmsService(KnowledgeArticleRepository orders,ContributionRecordRepository reports,ExpertRepository expert,ReviewTaskRepository reviewTasks,CurrentUserService current){this.orders=orders;this.reports=reports;this.expert=expert;this.reviewTasks=reviewTasks;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getKnowledgeSpaceCode();List<KnowledgeArticle> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByKnowledgeSpaceCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<KnowledgeArticleView> knowledgeArticles(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){KnowledgeArticle order=orders.findById(id).orElseThrow(()->new BusinessException("知识任务不存在"));if(order.getStatus()==KnowledgeArticle.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new ContributionRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<KnowledgeArticle> list){int planned=list.stream().mapToInt(KnowledgeArticle::getPlannedQty).sum(),done=list.stream().mapToInt(KnowledgeArticle::getCompletedQty).sum(),defects=list.stream().mapToInt(KnowledgeArticle::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日知识",String.format("%,d",planned),list.size()+" 张知识任务","blue"),new Metric("知识完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("专家异常",expert.countByStatus(Expert.Status.ALARM)+"",reviewTasks.countByResult(ReviewTask.Result.PENDING)+" 项待评审","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),expert.findAllByOrderByCodeAsc().stream().map(e->new ExpertView(e.getCode(),e.getName(),e.getKnowledgeSpace().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),reviewTasks.findTop10ByOrderByIdDesc().stream().map(i->new ReviewTaskView(i.getReviewTaskNo(),i.getKnowledgeArticle().getOrderNo(),i.getKnowledgeArticle().getProductName(),i.getReviewTaskType(),i.getReviewTaskQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private KnowledgeArticleView view(KnowledgeArticle o){return new KnowledgeArticleView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getKnowledgeSpace().getName(),o.getKnowledgeSpace().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(KnowledgeArticle o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
