/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.kms.service;import jakarta.validation.constraints.*;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class KnowledgePublicationGovernanceService{/**
                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                             */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(r.authorId().equals(r.reviewerId()))b.add("作者与审核人必须职责分离");if(!r.citationsVerified())b.add("事实引用尚未验证");if(r.confidentialContent()&&!r.accessPolicyConfigured())b.add("机密知识未配置访问策略");if(!r.finalApprovalComplete())b.add("最终发布审批未完成");if(!b.isEmpty()){a.add("阻断发布并补齐编审、引用和权限控制");return new Assessment(Decision.BLOCKED,b,a);}if(r.accessibilityScore()<80||!r.nextReviewDateAssigned()||!r.ownerAssigned()){if(r.accessibilityScore()<80)a.add("提升可访问性评分至至少 80");if(!r.nextReviewDateAssigned())a.add("设置下一次复审日期");if(!r.ownerAssigned())a.add("指定知识责任人");return new Assessment(Decision.REVIEW,b,a);}a.add("发布知识版本并记录责任人、复审日和审批证据");return new Assessment(Decision.PUBLISH,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record Request(@NotBlank String articleId,@NotBlank String authorId,@NotBlank String reviewerId,boolean citationsVerified,boolean confidentialContent,boolean accessPolicyConfigured,boolean finalApprovalComplete,@Min(0)@Max(100)int accessibilityScore,boolean nextReviewDateAssigned,boolean ownerAssigned){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public enum Decision{PUBLISH,REVIEW,BLOCKED}}
